name: docs
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    # https://docs.github.com/en/actions/guides/building-and-testing-python#installing-dependencies
    # ^-- This gives info on installing dependencies with pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx-rtd-theme
        pip install -r requirements.txt
        pip install -e .

    - name: Debugging information
      run: |
        echo "github.ref:" ${{github.ref}}
        echo "github.event_name:" ${{github.event_name}}
        echo "github.head_ref:" ${{github.head_ref}}
        echo "github.base_ref:" ${{github.base_ref}}
        set -x
        git rev-parse --abbrev-ref HEAD
        git branch
        git branch -a
        git remote -v
        python -V
        pip list --not-required
        pip list

    - name: Build Docs
      run: |
        make clean html
      working-directory: ./docs

    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
