name: docs
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements and Build Docs
      run: |
        pip3 install sphinx-rtd-theme
        pip3 install -r requirements.txt
        cd docs
        make clean html

    # Add the .nojekyll file
    - name: nojekyll
      if: ${{ github.event_name == 'push' }}
      run: |
        touch gh-pages/.nojekyll

    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
